services:
  tomee:
    image: tomee:jre17-webprofile
    container_name: tomee
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomee/webapps
      - scss:/src/local/tomee/webapps/helloweb/assets/scss
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
      MYSQL_USER: gabri
      MYSQL_PASSWORD: gabri
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
  nodediw-jsp:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ../vite/:/app
      - scss:/app/tomee

volumes:
  db_data:
  scss: